# New Section

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import learning_curve
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from math import sqrt
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.neural_network import MLPClassifier

In [ ]:

!pip install ipython-autotime
%load_ext autotime

Collecting ipython-autotime
  Downloading https://files.pythonhosted.org/packages/3f/58/a4a65efcce5c81a67b6893ade862736de355a3a718af5533d30c991831ce/ipython_autotime-0.2.0-py2.py3-none-any.whl
Requirement already satisfied: ipython in /usr/local/lib/python3.6/dist-packages (from ipython-autotime) (5.5.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from ipython->ipython-autotime) (4.4.2)
Requirement already satisfied: pygments in /usr/local/lib/python3.6/dist-packages (from ipython->ipython-autotime) (2.6.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.6/dist-packages (from ipython->ipython-autotime) (50.3.2)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from ipython->ipython-autotime) (4.8.0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.6/dist-packages (from ipython->ipython-autotime) (1.0.18)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/dist-packages (from ipython->ipython-autotime) (0.7.5)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.6/dist-packages (from ipython->ipython-autotime) (0.8.1)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.6/dist-packages (from ipython->ipython-autotime) (4.3.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/dist-packages (from pexpect; sys_platform != "win32"->ipython->ipython-autotime) (0.6.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->ipython-autotime) (0.2.5)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython->ipython-autotime) (1.15.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.2->ipython->ipython-autotime) (0.2.0)
Installing collected packages: ipython-autotime
Successfully installed ipython-autotime-0.2.0
time: 212 µs

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive
time: 22.2 s

Preprocessing of the dataset

In [ ]:
data = pd.read_csv("/content/gdrive/MyDrive/Taiwan Hospice Project/final.csv")

time: 2.71 s

In [ ]:
#Organize the data:
for i in range(1,46):
  if(i<10):
    name = 'HP0'+ str(i)
  else:
    name = 'HP'+ str(i)
  data.loc[data.PATIENT == name, 'dead'] = 0

time: 8 s

In [ ]:
dead_patients= ['06','07','08','11','12','14','17','20','21','22','23','25','29','32','35','37','40','42','45']
for i in dead_patients:
  name = 'HP'+i
  data.loc[data.PATIENT == name, 'dead'] = 1

time: 3.34 s

In [ ]:
data

            ACT  Angle  Spin PATIENT             DateTime  dead
0        168.00    3.0  12.0    HP01  2019-09-03 10:05:17   0.0
1        191.00    4.0  11.0    HP01  2019-09-03 10:05:27   0.0
2        211.00    3.0   0.0    HP01  2019-09-03 10:05:37   0.0
3         87.00    2.0   3.0    HP01  2019-09-03 10:05:47   0.0
4          7.19    3.0   1.0    HP01  2019-09-03 10:05:57   0.0
...         ...    ...   ...     ...                  ...   ...
2939766    1.81   15.0   0.0    HP45  2020-08-19 20:18:38   1.0
2939767    1.75   15.0   0.0    HP45  2020-08-19 20:18:48   1.0
2939768    1.56   15.0   0.0    HP45  2020-08-19 20:18:58   1.0
2939769    1.62   15.0   0.0    HP45  2020-08-19 20:19:08   1.0
2939770    1.94   15.0   0.0    HP45  2020-08-19 20:19:18   1.0

[2939771 rows x 6 columns]

time: 32.8 ms

In [ ]:
data = data[['ACT', 'Angle', 'Spin', 'PATIENT', 'DateTime', 'dead']]

time: 102 ms

In [ ]:
data.loc[data.PATIENT == 'HP01', 'Time'] = 19
data.loc[data.PATIENT == 'HP02', 'Time'] = 9
data.loc[data.PATIENT == 'HP03', 'Time'] = 4
data.loc[data.PATIENT == 'HP04', 'Time'] = 2
data.loc[data.PATIENT == 'HP05', 'Time'] = 11
data.loc[data.PATIENT == 'HP06', 'Time'] = 2
data.loc[data.PATIENT == 'HP07', 'Time'] = 4
data.loc[data.PATIENT == 'HP08', 'Time'] = 3
data.loc[data.PATIENT == 'HP09', 'Time'] = 2
data.loc[data.PATIENT == 'HP10', 'Time'] = 5
data.loc[data.PATIENT == 'HP11', 'Time'] = 11
data.loc[data.PATIENT == 'HP13', 'Time'] = 4
data.loc[data.PATIENT == 'HP14', 'Time'] = 14
data.loc[data.PATIENT == 'HP15', 'Time'] = 3
data.loc[data.PATIENT == 'HP16', 'Time'] = 23
data.loc[data.PATIENT == 'HP18', 'Time'] = 13
data.loc[data.PATIENT == 'HP20', 'Time'] = 1
data.loc[data.PATIENT == 'HP21', 'Time'] = 28
data.loc[data.PATIENT == 'HP22', 'Time'] = 24
data.loc[data.PATIENT == 'HP23', 'Time'] = 14
data.loc[data.PATIENT == 'HP24', 'Time'] = 5
data.loc[data.PATIENT == 'HP25', 'Time'] = 5
data.loc[data.PATIENT == 'HP28', 'Time'] = 4
data.loc[data.PATIENT == 'HP29', 'Time'] = 8
data.loc[data.PATIENT == 'HP30', 'Time'] = 17
data.loc[data.PATIENT == 'HP32', 'Time'] = 7
data.loc[data.PATIENT == 'HP33', 'Time'] = 9
data.loc[data.PATIENT == 'HP34', 'Time'] = 8
data.loc[data.PATIENT == 'HP35', 'Time'] = 2
data.loc[data.PATIENT == 'HP36', 'Time'] = 3
data.loc[data.PATIENT == 'HP37', 'Time'] = 5
data.loc[data.PATIENT == 'HP38', 'Time'] = 6
data.loc[data.PATIENT == 'HP39', 'Time'] = 15
data.loc[data.PATIENT == 'HP41', 'Time'] = 17
data.loc[data.PATIENT == 'HP42', 'Time'] = 2
data.loc[data.PATIENT == 'HP43', 'Time'] = 10
data.loc[data.PATIENT == 'HP44', 'Time'] = 9
data.loc[data.PATIENT == 'HP45', 'Time'] = 2

time: 6.75 s

In [ ]:
data.loc[data.PATIENT == 'HP01', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP02', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP03', 'kf_score'] = 40
data.loc[data.PATIENT == 'HP04', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP05', 'kf_score'] = 60
data.loc[data.PATIENT == 'HP06', 'kf_score'] = 10
data.loc[data.PATIENT == 'HP07', 'kf_score'] = 30
data.loc[data.PATIENT == 'HP08', 'kf_score'] = 20
data.loc[data.PATIENT == 'HP09', 'kf_score'] = 60
data.loc[data.PATIENT == 'HP10', 'kf_score'] = 40
data.loc[data.PATIENT == 'HP11', 'kf_score'] = 30
data.loc[data.PATIENT == 'HP13', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP14', 'kf_score'] = 40
data.loc[data.PATIENT == 'HP15', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP16', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP18', 'kf_score'] = 60
data.loc[data.PATIENT == 'HP20', 'kf_score'] = 10
data.loc[data.PATIENT == 'HP21', 'kf_score'] = 30
data.loc[data.PATIENT == 'HP22', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP23', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP24', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP25', 'kf_score'] = 40
data.loc[data.PATIENT == 'HP28', 'kf_score'] = 40
data.loc[data.PATIENT == 'HP29', 'kf_score'] = 30
data.loc[data.PATIENT == 'HP30', 'kf_score'] = 30
data.loc[data.PATIENT == 'HP32', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP33', 'kf_score'] = 40
data.loc[data.PATIENT == 'HP34', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP35', 'kf_score'] = 30
data.loc[data.PATIENT == 'HP36', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP37', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP38', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP39', 'kf_score'] = 60
data.loc[data.PATIENT == 'HP41', 'kf_score'] = 40
data.loc[data.PATIENT == 'HP42', 'kf_score'] = 10
data.loc[data.PATIENT == 'HP43', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP44', 'kf_score'] = 50
data.loc[data.PATIENT == 'HP45', 'kf_score'] = 40

time: 6.79 s

In [ ]:
data

            ACT  Angle  Spin PATIENT  ... dead  Time  kf_score  Primary_Diagnosis
0        168.00    3.0  12.0    HP01  ...  0.0  19.0      50.0                NaN
1        191.00    4.0  11.0    HP01  ...  0.0  19.0      50.0                NaN
2        211.00    3.0   0.0    HP01  ...  0.0  19.0      50.0                NaN
3         87.00    2.0   3.0    HP01  ...  0.0  19.0      50.0                NaN
4          7.19    3.0   1.0    HP01  ...  0.0  19.0      50.0                NaN
...         ...    ...   ...     ...  ...  ...   ...       ...                ...
2939766    1.81   15.0   0.0    HP45  ...  1.0   2.0      40.0                NaN
2939767    1.75   15.0   0.0    HP45  ...  1.0   2.0      40.0                NaN
2939768    1.56   15.0   0.0    HP45  ...  1.0   2.0      40.0                NaN
2939769    1.62   15.0   0.0    HP45  ...  1.0   2.0      40.0                NaN
2939770    1.94   15.0   0.0    HP45  ...  1.0   2.0      40.0                NaN

[2939771 rows x 9 columns]

time: 161 ms

Hot Encoding

In [ ]:
#data.set_value[(data.PATIENT, 'Primary_Diagnosis'):('HP01', 'Rectal Cancer', 'Lung Metastatis', 'Liver Metastatis')]
data.loc[data.PATIENT == 'HP01', 'Primary_Diagnosis']= ('Rectal Cancer, Lung Metastatis, Liver Metastatis')
data.loc[data.PATIENT == 'HP02', 'Primary_Diagnosis'] = ('Breat Cancer, Bone Metastatis, Brain Metastatis')
data.loc[data.PATIENT == 'HP03', 'Primary_Diagnosis'] = ('HCC, EV Bleeding')
data.loc[data.PATIENT == 'HP04', 'Primary_Diagnosis'] = ('Cervical Cancer, Malignant Ascites, Hyperthyroidism, Parkinsons')
data.loc[data.PATIENT == 'HP05', 'Primary_Diagnosis'] = ('Ovarian Cancer, Lymph nodes and Colon Invasion, Stage IV')
data.loc[data.PATIENT == 'HP06', 'Primary_Diagnosis'] = ('Rectal Cancer, Intra-abdominal seedings, Liver Metastatis, Type 2 DM')
data.loc[data.PATIENT == 'HP07', 'Primary_Diagnosis'] = ('Lung Cancer, Brain Metastatis, DM, Hypertension')
data.loc[data.PATIENT == 'HP08', 'Primary_Diagnosis'] = ('Lung Cancer, Diffuse Liver Metastatis, Hypertension')
data.loc[data.PATIENT == 'HP09', 'Primary_Diagnosis'] = ('Left Buccal Squamous Cell Carcinoma, Left Retromolar Cancer, Right Posterior Tongue Cancer, Left Tongue Cancer, Type 2 DM, Hypertension')
data.loc[data.PATIENT == 'HP10', 'Primary_Diagnosis'] = ('Rectal Adenocarcinoma, Lung Metastatis, Liver Metastatis, Chronic Hepatitis B')
data.loc[data.PATIENT == 'HP11', 'Primary_Diagnosis'] = ('High Grade Glioma at pons, Chronic Kidney Disease, Hypertensive Heart Disease, Heart Failure')
data.loc[data.PATIENT == 'HP13', 'Primary_Diagnosis'] = ('Ovarian Cancer Adenocarcinoma, Right Breast Cancer, Carcinoma in situ 3 of Cervix')
data.loc[data.PATIENT == 'HP14', 'Primary_Diagnosis'] = ('Lung Squamous Cell Carcinoma, Psoriasis Vulgaris, Hypertension, Old Cerebrovascular Accident')
data.loc[data.PATIENT == 'HP15', 'Primary_Diagnosis'] = ('Lower Third Esophageal Squamous Cell Carcinoma, Valvular Heart Disease, Aortic Regurgitation, Pulmonary Hypertension, Tricuspid Regurgitation')
data.loc[data.PATIENT == 'HP16', 'Primary_Diagnosis'] = ('Right Breast Cancer, Lung Metastatis, Adenocarcinoma of Ascending Colon, Bone Metastatis, Femoral Basal Fracture, Clavicle Fracture, Hypertension, DM')
data.loc[data.PATIENT == 'HP18', 'Primary_Diagnosis'] = ('Prostate Cancer, Brain Metastatis, Multiple Bone Metastatis, Liver Metastatis, Type 2 DM, Hypertension')
data.loc[data.PATIENT == 'HP20', 'Primary_Diagnosis'] = ('Prostate Cancer, COPD, Ischemic Heart Disease, Asthma, ICH, SAH, IVH, Recurrent Sigmoid Volvulus')
data.loc[data.PATIENT == 'HP21', 'Primary_Diagnosis'] = ('GBM Grade 4, Coronary Artery Disease, Double Vessel Disease, Hyperuricemia, Hyperlipidemia, Asthma, Hypertension, Type 2 DM')
data.loc[data.PATIENT == 'HP22', 'Primary_Diagnosis'] = ('Lung Adenocarcinoma, Brain Metastatis, Bone Metastatis')
data.loc[data.PATIENT == 'HP23', 'Primary_Diagnosis'] = ('Rectal Adenocarcinoma, Liver Metastatis, Coronary Artery Disease')
data.loc[data.PATIENT == 'HP24', 'Primary_Diagnosis'] = ('Colon Cancer, Lung Metastatis, Liver Metastatis, Hypertension')
data.loc[data.PATIENT == 'HP25', 'Primary_Diagnosis'] = ('Sigmoid Colon Cancer, Lymph Node Metastatis, Mesenteric Seeding')
data.loc[data.PATIENT == 'HP28', 'Primary_Diagnosis'] = ('Gastric Poorly Differentiatied Adenocarcinoma, Sjogrens Syndrome, Hypertension, Arrythmia')
data.loc[data.PATIENT == 'HP29', 'Primary_Diagnosis'] = ('Hepatocellular Carcinoma, Acute Coronary Syndrome')
data.loc[data.PATIENT == 'HP30', 'Primary_Diagnosis'] = ('Gastric Cancer')
data.loc[data.PATIENT == 'HP32', 'Primary_Diagnosis'] = ('Vaginal Cancer, Lung Metastatis')
data.loc[data.PATIENT == 'HP33', 'Primary_Diagnosis'] = ('Gastric Poorly Differentiated Adenocarcinoma, Spine Metastatis')
data.loc[data.PATIENT == 'HP34', 'Primary_Diagnosis'] = ('Prostate Cancer, Spine Metastatis')
data.loc[data.PATIENT == 'HP35', 'Primary_Diagnosis'] = ('Prostate Cancer, Lung Metastatis, Liver Metastatis, Bone Metastatis')
data.loc[data.PATIENT == 'HP36', 'Primary_Diagnosis'] = ('Gastric Cancer, Peritoneal Seeding, Right Lower Lung Non-Small Cell Carcinoma')
data.loc[data.PATIENT == 'HP37', 'Primary_Diagnosis'] = ('None')
data.loc[data.PATIENT == 'HP38', 'Primary_Diagnosis'] = ('Sigmoid Adenocarcinoma, Liver Metastatis')
data.loc[data.PATIENT == 'HP39', 'Primary_Diagnosis'] = ('Left Upper Lobe Adenocarcinoma, Left Malignant Pleural Metastatis, Bone Metastatis')
data.loc[data.PATIENT == 'HP41', 'Primary_Diagnosis'] = ('Prostate Cancer, Multiple Bone Metastatis, Lower Limbs Paralysis')
data.loc[data.PATIENT == 'HP42', 'Primary_Diagnosis'] = ('Bladder Urothelial Carcinoma, Lung Metastatis')
data.loc[data.PATIENT == 'HP43', 'Primary_Diagnosis'] = ('Lower Third Esophageal Squamous Cell Carcinoma')
data.loc[data.PATIENT == 'HP44', 'Primary_Diagnosis'] = ('Ampullavater Adenocarcinoma, Liver Metastatis')
data.loc[data.PATIENT == 'HP45', 'Primary_Diagnosis'] = ('Sigmoid Colon Adenocarcinoma, Liver Metastatis, Multiple Peritoneal Tumor Seedings')

time: 8.62 s

In [ ]:
data = pd.concat([data, data['Primary_Diagnosis'].str.get_dummies(sep=',')], axis = 1).drop('Primary_Diagnosis', 1)

time: 2min 7s

In [ ]:
data

            ACT  Angle  ...  Sigmoid Colon Cancer Vaginal Cancer
0        168.00    3.0  ...                     0              0
1        191.00    4.0  ...                     0              0
2        211.00    3.0  ...                     0              0
3         87.00    2.0  ...                     0              0
4          7.19    3.0  ...                     0              0
...         ...    ...  ...                   ...            ...
2939766    1.81   15.0  ...                     0              0
2939767    1.75   15.0  ...                     0              0
2939768    1.56   15.0  ...                     0              0
2939769    1.62   15.0  ...                     0              0
2939770    1.94   15.0  ...                     0              0

[2939771 rows x 62 columns]

time: 148 ms

In [ ]:
data.to_csv(r'/content/gdrive/MyDrive/Taiwan Hospice Project/PrimaryDiagnosisAdded.csv', index = False)

time: 40.7 s

Summa test Panrathu

In [ ]:
data.loc[data.PATIENT == 'HP01'].index[-1]
for i in range(1,46):
  start = data.loc[data.PATIENT == 'HP01'].index[0]
  end = data.loc[data.PATIENT == 'HP01'].index[-1]

161121

time: 173 ms

In [ ]:
dummy = data.iloc[0:161122]
dummy['Primary_Diagnosis'] = ('Rectal Cancer, Lung Metastatis, Liver Metastatis')

time: 4.37 ms

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
dummy['Primary_Diagnosis'].str.get_dummies(sep=',')

         Liver Metastatis   Lung Metastatis  Rectal Cancer
0                       1                 1              1
1                       1                 1              1
2                       1                 1              1
3                       1                 1              1
4                       1                 1              1
...                   ...               ...            ...
161117                  1                 1              1
161118                  1                 1              1
161119                  1                 1              1
161120                  1                 1              1
161121                  1                 1              1

[161122 rows x 3 columns]

time: 1.02 s

In [ ]:
dummy = pd.concat([dummy, dummy['Primary_Diagnosis'].str.get_dummies(sep=',')], axis = 1).drop('Primary_Diagnosis', 1)

time: 1.08 s

In [ ]:
dummy['Primary_Diagnosis'].str.get_dummies(sep=',')

time: 1.01 s

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
dummy

           ACT  Angle  Spin  ...  Liver Metastatis  Lung Metastatis  Rectal Cancer
0       168.00    3.0  12.0  ...                 1                1              1
1       191.00    4.0  11.0  ...                 1                1              1
2       211.00    3.0   0.0  ...                 1                1              1
3        87.00    2.0   3.0  ...                 1                1              1
4         7.19    3.0   1.0  ...                 1                1              1
...        ...    ...   ...  ...               ...              ...            ...
161117    1.75    4.0  15.0  ...                 1                1              1
161118    2.12    4.0  15.0  ...                 1                1              1
161119    1.75    4.0  15.0  ...                 1                1              1
161120    1.69    4.0  15.0  ...                 1                1              1
161121    1.75    4.0  15.0  ...                 1                1              1

[161122 rows x 11 columns]

time: 41.8 ms

In [ ]:
pd.get_dummies(dummy.Primary_Diagnosis)

        Rectal Cancer, Lung Metastatis, Liver Metastatis
0                                                      1
1                                                      1
2                                                      1
3                                                      1
4                                                      1
...                                                  ...
161117                                                 1
161118                                                 1
161119                                                 1
161120                                                 1
161121                                                 1

[161122 rows x 1 columns]

time: 32 ms

In [ ]:
dummy

           ACT  Angle  Spin PATIENT  ... dead  Time  kf_score  Primary_Diagnosis
0       168.00    3.0  12.0    HP01  ...  0.0  19.0      50.0             Cancer
1       191.00    4.0  11.0    HP01  ...  0.0  19.0      50.0             Cancer
2       211.00    3.0   0.0    HP01  ...  0.0  19.0      50.0             Cancer
3        87.00    2.0   3.0    HP01  ...  0.0  19.0      50.0             Cancer
4         7.19    3.0   1.0    HP01  ...  0.0  19.0      50.0             Cancer
...        ...    ...   ...     ...  ...  ...   ...       ...                ...
161117    1.75    4.0  15.0    HP01  ...  0.0  19.0      50.0             Cancer
161118    2.12    4.0  15.0    HP01  ...  0.0  19.0      50.0             Cancer
161119    1.75    4.0  15.0    HP01  ...  0.0  19.0      50.0             Cancer
161120    1.69    4.0  15.0    HP01  ...  0.0  19.0      50.0             Cancer
161121    1.75    4.0  15.0    HP01  ...  0.0  19.0      50.0             Cancer

[161122 rows x 9 columns]

time: 47.2 ms

In [ ]:
data

            ACT  Angle  Spin PATIENT  ... dead  Time  kf_score  Primary_Diagnosis
0        168.00    3.0  12.0    HP01  ...  0.0  19.0      50.0                NaN
1        191.00    4.0  11.0    HP01  ...  0.0  19.0      50.0                NaN
2        211.00    3.0   0.0    HP01  ...  0.0  19.0      50.0                NaN
3         87.00    2.0   3.0    HP01  ...  0.0  19.0      50.0                NaN
4          7.19    3.0   1.0    HP01  ...  0.0  19.0      50.0                NaN
...         ...    ...   ...     ...  ...  ...   ...       ...                ...
2939766    1.81   15.0   0.0    HP45  ...  1.0   2.0      40.0                NaN
2939767    1.75   15.0   0.0    HP45  ...  1.0   2.0      40.0                NaN
2939768    1.56   15.0   0.0    HP45  ...  1.0   2.0      40.0                NaN
2939769    1.62   15.0   0.0    HP45  ...  1.0   2.0      40.0                NaN
2939770    1.94   15.0   0.0    HP45  ...  1.0   2.0      40.0                NaN

[2939771 rows x 9 columns]

time: 156 ms

In [ ]:
data = data.dropna(subset=['PATIENT', 'DateTime', 'Time', 'ACT', 'Angle', 'Spin', 'dead', 'kf_score'])

KeyError: ignored

time: 9.64 ms

In [ ]:
data = data[['DateTime', 'Time', 'ACT', 'Angle', 'Spin', 'dead', 'kf_score']]

KeyError: ignored

time: 16.7 ms

In [ ]:
data

                    DateTime  Time     ACT  Angle  Spin  dead  kf_score
0        2019-09-03 10:05:17  19.0  168.00    3.0  12.0   0.0      50.0
1        2019-09-03 10:05:27  19.0  191.00    4.0  11.0   0.0      50.0
2        2019-09-03 10:05:37  19.0  211.00    3.0   0.0   0.0      50.0
3        2019-09-03 10:05:47  19.0   87.00    2.0   3.0   0.0      50.0
4        2019-09-03 10:05:57  19.0    7.19    3.0   1.0   0.0      50.0
...                      ...   ...     ...    ...   ...   ...       ...
2939766  2020-08-19 20:18:38   2.0    1.81   15.0   0.0   1.0      40.0
2939767  2020-08-19 20:18:48   2.0    1.75   15.0   0.0   1.0      40.0
2939768  2020-08-19 20:18:58   2.0    1.56   15.0   0.0   1.0      40.0
2939769  2020-08-19 20:19:08   2.0    1.62   15.0   0.0   1.0      40.0
2939770  2020-08-19 20:19:18   2.0    1.94   15.0   0.0   1.0      40.0

[2939771 rows x 7 columns]

time: 28.2 ms

In [ ]:
data.describe()

               Time           ACT  ...          dead      kf_score
count  2.939771e+06  2.939771e+06  ...  2.939771e+06  2.939771e+06
mean   1.394875e+01  7.676912e+00  ...  4.269873e-01  4.515630e+01
std    7.538866e+00  4.142520e+01  ...  4.946405e-01  1.028970e+01
min    1.000000e+00  0.000000e+00  ...  0.000000e+00  1.000000e+01
25%    8.000000e+00  0.000000e+00  ...  0.000000e+00  4.000000e+01
50%    1.400000e+01  3.310000e+00  ...  0.000000e+00  5.000000e+01
75%    1.900000e+01  7.508571e+00  ...  1.000000e+00  5.000000e+01
max    2.800000e+01  6.080000e+03  ...  1.000000e+00  6.000000e+01

[8 rows x 6 columns]

time: 422 ms

Defining Our Model

In [ ]:
X = data.drop(["Time", "dead"], axis=1)

In [ ]:
y = data[["Time", "dead"]]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

In [ ]:
X_train.shape

In [ ]:
X_test.shape

Standardisation of the defined model

In [ ]:
scaler = StandardScaler()

In [ ]:
train_scaled = scaler.fit_transform(X_train)

In [ ]:
test_scaled = scaler.transform(X_test)

1. a. Linear Regression Model

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(train_scaled, y_train)

In [ ]:
mse = mean_squared_error(y_train, model.predict(train_scaled))
mae = mean_absolute_error(y_train, model.predict(train_scaled))

In [ ]:
print("mse = ",mse," & mae = ",mae," & rmse = ", sqrt(mse))

In [ ]:
test_array = model.predict(test_scaled)

In [ ]:
test_mse = mean_squared_error(y_test, model.predict(test_scaled))
test_mae = mean_absolute_error(y_test, model.predict(test_scaled))
print("mse = ",test_mse," & mae = ",test_mae," & rmse = ", sqrt(test_mse))

In [ ]:
a = int(test_array.size/3)
for i in range(0,a):
  if(test_array[i][1])>=0.5:
    test_array[i][1]=1.0
  else:
    test_array[i][1]=0.0
  test_array[i][0]=int(test_array[i][0])
  test_array[i][2]=int(test_array[i][2])

In [ ]:
test_mse = mean_squared_error(y_test, test_array)
test_mae = mean_absolute_error(y_test, test_array)
print("mse = ",test_mse," & mae = ",test_mae," & rmse = ", sqrt(test_mse))

In [ ]:
test_array

In [ ]:
X_test

6. a. Multi-Layer Perceptron Classifier Neural Network Model

In [ ]:
y_train=y_train.astype('int')

In [ ]:
y_test=y_test.astype('int')

In [ ]:
from sklearn.neural_network import MLPRegressor
mlp = MLPRegressor(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
mlp.fit(train_scaled,y_train)
predict_train = mlp.predict(train_scaled)
predict_test = mlp.predict(test_scaled)

In [ ]:
mlp.score(X_test, test_scaled)

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes=(250,200,150), activation='softmax', solver='adam', max_iter=15,)
mlp.fit(train_scaled,y_train)

predict_train = mlp.predict(train_scaled)
predict_test = mlp.predict(test_scaled)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

In [ ]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

6. b. Learning Curve plot for Multi-Layer Perceptron Classifier Model

In [ ]:
train_sizes = [1, 100, 500, 2000, 5000, 7654]

In [ ]:
train_sizes, train_scores, validation_scores = learning_curve(
estimator = MLPClassifier(hidden_layer_sizes=(250,200,150), activation='relu', solver='adam', max_iter=15),
X = X_train,
y = y_train, train_sizes = train_sizes, cv = 5,
scoring = 'neg_mean_squared_error')

In [ ]:
train_scores_mean = -train_scores.mean(axis = 1)
validation_scores_mean = -validation_scores.mean(axis = 1)

In [ ]:
plt.style.use('seaborn')
plt.plot(train_sizes, train_scores_mean, label = 'Training error')
plt.plot(train_sizes, validation_scores_mean, label = 'Validation error')
plt.ylabel('MSE', fontsize = 14)
plt.xlabel('Training set size', fontsize = 14)
plt.title('Learning curves for a Multi Layer Perceptron Classifier model', fontsize = 18, y = 1.03)
plt.legend()
#plt.ylim(100,100)

4. a. Gradient Boosting Classifier Model

In [ ]:
y_train=y_train.astype('int')

In [ ]:
y_test=y_test.astype('int')

In [ ]:
clf = GradientBoostingClassifier(random_state=0)
clf.fit(train_scaled, y_train)

In [ ]:
clf.score(test_scaled, y_test)

In [ ]:
clf.score(train_scaled, y_train)

In [ ]:
clf.predict(train_scaled)

In [ ]:
clf.predict(test_scaled)

4. b. Learning Curve plot for Gradient Boosting Classifier Model

In [ ]:
train_sizes = [1, 100, 500, 2000, 5000, 7654]

In [ ]:
train_sizes, train_scores, validation_scores = learning_curve(
estimator = GradientBoostingClassifier(random_state=0),
X = X_train,
y = y_train, train_sizes = train_sizes, cv = 5,
scoring = 'neg_mean_squared_error')

In [ ]:
train_scores_mean = -train_scores.mean(axis = 1)
validation_scores_mean = -validation_scores.mean(axis = 1)

In [ ]:
plt.style.use('seaborn')
plt.plot(train_sizes, train_scores_mean, label = 'Training error')
plt.plot(train_sizes, validation_scores_mean, label = 'Validation error')
plt.ylabel('MSE', fontsize = 14)
plt.xlabel('Training set size', fontsize = 14)
plt.title('Learning curves for a Gradient Boosting Regression model', fontsize = 18, y = 1.03)
plt.legend()
#plt.ylim(100,100)

In [ ]:
tree_model = DecisionTreeRegressor()
rf_model = RandomForestRegressor()

In [ ]:
tree_model.fit(train_scaled, y_train)
rf_model.fit(train_scaled, y_train)

In [ ]:
tree_mse = mean_squared_error(y_train, tree_model.predict(train_scaled))
tree_mae = mean_absolute_error(y_train, tree_model.predict(train_scaled))
rf_mse = mean_squared_error(y_train, rf_model.predict(train_scaled))
rf_mae = mean_absolute_error(y_train, rf_model.predict(train_scaled))

In [ ]:
print("Decision Tree training mse = ",tree_mse," & mae = ",tree_mae," & rmse = ", sqrt(tree_mse))
print("Random Forest training mse = ",rf_mse," & mae = ",rf_mae," & rmse = ", sqrt(rf_mse))

In [ ]:
tree_test_mse = mean_squared_error(y_test, tree_model.predict(test_scaled))
tree_test_mae = mean_absolute_error(y_test, tree_model.predict(test_scaled))
rf_test_mse = mean_squared_error(y_test, rf_model.predict(test_scaled))
rf_test_mae = mean_absolute_error(y_test, rf_model.predict(test_scaled))

In [ ]:
print("Decision Tree test mse = ",tree_test_mse," & mae = ",tree_test_mae," & rmse = ", sqrt(tree_test_mse))
print("Random Forest test mse = ",rf_test_mse," & mae = ",rf_test_mae," & rmse = ", sqrt(rf_test_mse))

In [ ]:
install.packages("gbm")
library(gbm)

In [ ]:
from sklearn import ensemble
from sklearn.multioutput import MultiOutputRegressor

...

params = {'n_estimators': 5000, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 2
         }

estimator = MultiOutputRegressor(ensemble.GradientBoostingRegressor(**params))
estimator.fit(X_train,train_scaled)

In [ ]:
estimator.score(X_test, test_scaled)

In [ ]:
import math
import matplotlib.pyplot as plt
import keras
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import *
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping

In [ ]:
model.summary()

In [ ]:
model = Sequential()
#Adding the first LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
# Adding a second LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
# Adding a third LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))
# Adding a fourth LSTM layer and some Dropout regularisation
model.add(LSTM(units = 50))
model.add(Dropout(0.2))
# Adding the output layer
model.add(Dense(units = 1))
# Compiling the RNN
model.compile(optimizer = 'adam', loss = 'mean_squared_error')
# Fitting the RNN to the Training set
model.fit(X_train, y_train, epochs = 100, batch_size = 32)
model.summary()

In [ ]:
dada

In [ ]:
dadad

In [ ]:
data.iloc[0,1:2]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM
#dataframe creation
#seriesdata = todataframe.sort_index(ascending=True, axis=0)
seriesdata  = data
new_seriesdata = data[['DateTime','dead']]
length_of_data=len(seriesdata)

#setting the index again
new_seriesdata.index = new_seriesdata.DateTime
new_seriesdata.drop('DateTime', axis=1, inplace=True)
#creating train and test sets this comprises the entire data’s present in the dataset
myseriesdataset = new_seriesdata.values
totrain = myseriesdataset[0:255,:]
tovalid = myseriesdataset[255:,:]
#converting dataset into x_train and y_train
scalerdata = MinMaxScaler(feature_range=(0, 1))
scale_data = scalerdata.fit_transform(myseriesdataset)
x_totrain, y_totrain = [], []
length_of_totrain=len(totrain)
for i in range(60,length_of_totrain):
    x_totrain.append(scale_data[i-60:i,0])
    y_totrain.append(scale_data[i,0])
x_totrain, y_totrain = np.array(x_totrain), np.array(y_totrain)
x_totrain = np.reshape(x_totrain, (x_totrain.shape[0],x_totrain.shape[1],1))
#LSTM neural network
lstm_model = Sequential()
lstm_model.add(LSTM(units=50, return_sequences=True, input_shape=(x_totrain.shape[1],1)))
lstm_model.add(LSTM(units=50))
lstm_model.add(Dense(1))
lstm_model.compile(loss='mean_squared_error', optimizer='adadelta')
lstm_model.fit(x_totrain, y_totrain, epochs=3, batch_size=1, verbose=2)
#predicting next data stock price
myinputs = new_seriesdata[len(new_seriesdata) - (len(tovalid)+1) - 60:].values
myinputs = myinputs.reshape(-1,1)
myinputs  = scalerdata.transform(myinputs)
tostore_test_result = []
for i in range(60,myinputs.shape[0]):
    tostore_test_result.append(myinputs[i-60:i,0])
tostore_test_result = np.array(tostore_test_result)
tostore_test_result = np.reshape(tostore_test_result,(tostore_test_result.shape[0],tostore_test_result.shape[1],1))
myclosing_priceresult = lstm_model.predict(tostore_test_result)
myclosing_priceresult = scalerdata.inverse_transform(myclosing_priceresult)